### ISSUE TITLE
Mechanism to disable report-uri from the server and/or user-agent?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-error-logging#14]
Imagine the following:
1. A very high hit domain such as doubleclick chooses to implement reporting on this
2. That domain is blocked at by corporate IT at a company.

The number of events sent via Http could be very high for a very long time.

Would it make sense to add a count field so multiple entries can be combined?

**Comment by igrigorik** [comment]
I don't think `count` would solve the scenario you've outlined... The user-agent is online hence it should attempt to deliver the report shortly after the error occurs because we want to provide near-real time feedback to the site (note that the report origin should also be different from NEL host's to enable this). But, the user will continue to encounter these errors as they go about their business. Hence `count` might provide a small gain where back-to-back reports are issued, but it wouldn't stem the overall flow of these reports. Further, `count` alone is insufficient since every report has unique data for things like elapsed-time, age, etc.

In terms of mitigating this...  The site *is* in control to whom it advertises its NEL policy, so the site can disable the reporting functionality for some or all of the affected users (based on set cookie, IP block, etc).

**Comment by toddreifsteck** [comment]
Interesting.. it adds complexity but should the report URL be able to reply to suppress the NEL entry? I'm admittedly brainstorming solutions to a problem that may not exist. What has the experience of Domain Reliability Monitoring shown in large scale outages? (Past experience as a server-side developer in Azure may be making me overthink this issue.)

**Comment by igrigorik** [comment]
In DR we experimented with configurable sampling - i.e. allow the policy to define the probability that the report should be sent. However, DR also beaconed "success" navigations, which is a feature we're omitting in NER (it's out of scope and this data can already be gathered via other means). 

In practice, looking at the [configs for deployed DR sites](https://code.google.com/p/chromium/codesearch#search/&q=failure_sample_rate%20package:%5Echromium$%20file:(%5Esrc/components/domain_reliability/baked_in_configs/)&type=cs) you can see that all error rates ended up as 1.0.. so, no sampling, and this has not been an issue to date. With that in mind, and to keep things simple I punted on sampling when drafting the new spec.. That's not to say that this can't or shouldn't be added back, but personally I'd love to see some real world data showing that it is a necessary feature first? So far, the Google experience seems to show otherwise.

> Interesting.. it adds complexity but should the report URL be able to reply to suppress the NEL entry?

I think this is reasonable. For example, we could spec that if server returns 410 (or whatever code that is the best semantic fit here /cc @mnot), then the UA should unregister the policy? Similarly, if the server returns 5XX after X retries, unregister the policy? 

Using above mechanism the NEL collector would have a fairly simple "load shedding" strategy: return 4XX to disable NEL on some fraction of hosts if the error rate is spiking?

**Comment by AloisReitbauer** [comment]
I agree with Ilya. Providing RUM endpoints we already get traffic from high traffic sites. NEL data would just be another data source. If we still want a secure means for an endpoint to turn off logging, the server can return a 400 error code indicating that no future requests are allowed.

**Comment by toddreifsteck** [comment]
I am not 100% sure we need a solution here but wanted to be sure we considered the issue. The 400/500 turning off NEL strikes me as a good solution if/when we believe we need to add a way to turn NEL off.

**Comment by igrigorik** [comment]
Pedantic.. we do have a way to disable an NEL: the origin returns an NEL policy with [max-age set to zero](https://w3c.github.io/navigation-error-logging/#the-max-age-directive).

I guess what we're discussing here is: **should the report-uri origin have a way to take itself out of the policy?** It does seem like a reasonable requirement to me.

* The NEL policy can have multiple report-uri's, so if we allow this then the origin can respond with a particular error code (suggestions?) to take itself out of the policy.
* Once all report-uri's have been disabled, the UA removes the NEL policy registration on its end.

**Comment by toddreifsteck** [comment]
A CORS refusal should remove the report Uri so 410 is clearly one of the status codes that should remove a report-uri from the list.

Would it make sense to remove a report-uri in the case of any 4XX/5XX error?
(The only case I imagine being tricky here is 404. A flaky network could cause 404s to trigger for reports that we’d like to see delivered.)

**Comment by igrigorik** [comment]
@toddreifsteck hmm, the CORS spec specifically excludes 410 from "network error" in [7.1.4](http://www.w3.org/TR/cors/#simple-cross-origin-request-0).

I think there are two cases here: 
- a) An error code to immediately disable a report-uri origin - e.g. reporting origin wants to shed load. 
- b) UA policy for dealing with report-uri origins that report errors - i.e. should the UA just continue retrying indefinitely, or should it remove the origin from report-uri list after X failed retries (e.g. remove report-uri after N 4xx/5xx responses).

I'll check in on (a) with the DR folks at Google -- not sure if this is a nice to have or must have. For (b), it seems like a sensible thing for UA to have.. Otherwise you might end up accumulating dead hosts and doing lots of unnecessary work.

_p.s. updating title of the bug to reflect the discussion.._

**Comment by toddreifsteck** [comment]
My specific point was a subset of b--We should disable the report-uri if CORs checks are failed.

(I was rushing through the CORs spec and wasn’t even thinking of how it actually works in my rush for a status code…)

**Comment by igrigorik** [comment]
@toddreifsteck I don't think NEL is subject to CORS: (a) registration happens over HTTPS and origin explicitly states list of report-uri's; (b) application code can't arbitrarily change this registration; (c) UA controls when reports are delivered. As such, the server grants explicit permission upfront and there is no "client-side" scripting here - everything is controlled by the UA.

**Comment by toddreifsteck** [comment]
What protects report-uri from garbage data being sent to it via any random xhr request?

**Comment by igrigorik** [comment]
@toddreifsteck CORS :) ... CORS and CSP restrict which requests can be initiated by the application code. However, those are orthogonal to UA-initiated navigation error reports, which is what we're discussing here. If your app wants to generate own ~NEL-like reports and beacon them via XHR to same report-uri origin, then those XHR's must pass the right CORS checks - preflight, etc.

**Comment by toddreifsteck** [comment]
I’m considering the entire scenario from site adding the NEL header to the UA-Agent to the report-uri site and considering potential issues that could be a reason to disable NEL.

If a site foo.malicous.com adds a report-uri via NEL for googlereport-uri.com, what is the mitigation?

Without a CORS preflight check, googlereport-uri.com has to deal with filtering NELs.

**Comment by igrigorik** [comment]
> If a site foo.malicous.com adds a report-uri via NEL for googlereport-uri.com, what is the mitigation?

- googlereport.uri.com receives report from foo.malicious.com and perform an Origin check
- If the advertised Origin value does not match what it expects it returns a 4XX code that removes it from the NEL policy

Assuming we have a compliant UA, the overhead would be at most one request. Reasonable? The same workflow also applies to load shedding - e.g. googlereport-uri.com is receiving too many reports and starts returning 4XX to some portion of users.

**Comment by igrigorik** [comment]
@toddreifsteck ptal @ https://github.com/w3c/navigation-error-logging/pull/29/files - does that work?
